/* amlaboutdialog.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __AMLABOUTDIALOG_H__
#define __AMLABOUTDIALOG_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS
#define TYPE_AML_ABOUT_DIALOG (aml_about_dialog_get_type ())
#define AML_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AML_ABOUT_DIALOG, AmlAboutDialog))
#define AML_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_AML_ABOUT_DIALOG, AmlAboutDialogClass))
#define IS_AML_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AML_ABOUT_DIALOG))
#define IS_AML_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_AML_ABOUT_DIALOG))
#define AML_ABOUT_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AML_ABOUT_DIALOG, AmlAboutDialogClass))
typedef struct _AmlAboutDialog AmlAboutDialog;
typedef struct _AmlAboutDialogClass AmlAboutDialogClass;
typedef struct _AmlAboutDialogPrivate AmlAboutDialogPrivate;

struct _AmlAboutDialog {
    GtkAboutDialog parent_instance;
    AmlAboutDialogPrivate *priv;
};

struct _AmlAboutDialogClass {
    GtkAboutDialogClass parent_class;
};


GType aml_about_dialog_get_type(void) G_GNUC_CONST;
AmlAboutDialog *aml_about_dialog_new(void);
AmlAboutDialog *aml_about_dialog_construct(GType object_type);

#define aml_about_dialog_run(dialog)    gtk_dialog_run(GTK_DIALOG(dialog))
#define aml_about_dialog_destroy(dialog) gtk_widget_destroy(GTK_WIDGET(dialog))


G_END_DECLS
#endif
