/* amlaboutdialog.c generated by valac 0.20.1, the Vala compiler
 * generated from amlaboutdialog.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "amlaboutdialog.h"


#define PROGRAM_NAME "AML"
#define AML_WEBSITE "https://github.com/wiiiky/aml"
#define AML_COMMENTS "Android Manager for Linux"
#define AML_COPYRIGH "Copyright (c) Wiky L"
#define AML_VERSION "0.1"

const static gchar *AML_AUTHORS[] = {
    "Wiky L (wiiiky@yeah.net)",
    NULL
};


static gpointer aml_about_dialog_parent_class = NULL;

enum {
    AML_ABOUT_DIALOG_DUMMY_PROPERTY
};


AmlAboutDialog *aml_about_dialog_construct(GType object_type)
{
    AmlAboutDialog *self = NULL;
    self = (AmlAboutDialog *) g_object_new(object_type, NULL);
    return self;
}


AmlAboutDialog *aml_about_dialog_new(void)
{
    return aml_about_dialog_construct(TYPE_AML_ABOUT_DIALOG);
}


static void aml_about_dialog_class_init(AmlAboutDialogClass * klass)
{
    aml_about_dialog_parent_class = g_type_class_peek_parent(klass);
}


static void aml_about_dialog_instance_init(AmlAboutDialog * self)
{
    gtk_about_dialog_set_program_name(GTK_ABOUT_DIALOG(self),
                                      PROGRAM_NAME);
    gtk_about_dialog_set_version(GTK_ABOUT_DIALOG(self), AML_VERSION);
    gtk_about_dialog_set_license_type(GTK_ABOUT_DIALOG(self),
                                      GTK_LICENSE_GPL_3_0);
    gtk_about_dialog_set_copyright(GTK_ABOUT_DIALOG(self), AML_COPYRIGH);
    gtk_about_dialog_set_comments(GTK_ABOUT_DIALOG(self), AML_COMMENTS);
    gtk_about_dialog_set_website(GTK_ABOUT_DIALOG(self), AML_WEBSITE);
    gtk_about_dialog_set_authors(GTK_ABOUT_DIALOG(self), AML_AUTHORS);
}


GType aml_about_dialog_get_type(void)
{
    static volatile gsize aml_about_dialog_type_id__volatile = 0;
    if (g_once_init_enter(&aml_about_dialog_type_id__volatile)) {
        static const GTypeInfo g_define_type_info =
            { sizeof(AmlAboutDialogClass), (GBaseInitFunc) NULL,
            (GBaseFinalizeFunc) NULL,
            (GClassInitFunc) aml_about_dialog_class_init,
            (GClassFinalizeFunc) NULL,
            NULL, sizeof(AmlAboutDialog), 0,
            (GInstanceInitFunc) aml_about_dialog_instance_init, NULL
        };
        GType aml_about_dialog_type_id;
        aml_about_dialog_type_id =
            g_type_register_static(GTK_TYPE_ABOUT_DIALOG, "AmlAboutDialog",
                                   &g_define_type_info, 0);
        g_once_init_leave(&aml_about_dialog_type_id__volatile,
                          aml_about_dialog_type_id);
    }
    return aml_about_dialog_type_id__volatile;
}
