/* AmlApplicationView.c generated by valac 0.20.1, the Vala compiler
 * generated from AmlApplicationView.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "amlapplicationview.h"
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AmlApplicationViewPrivate {
    GtkTreeView *appView;
    GtkListStore *appStore;
};


static gpointer aml_application_view_parent_class = NULL;

#define AML_APPLICATION_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_AML_APPLICATION_VIEW, AmlApplicationViewPrivate))
enum {
    AML_APPLICATION_VIEW_DUMMY_PROPERTY
};
static void aml_application_view_finalize(GObject * obj);

typedef enum {
    AML_APPLICATION_VIEW_COL_ICON,
    AML_APPLICATION_VIEW_COL_NAME,
    AML_APPLICATION_VIEW_COL_VERSION,
    AML_APPLICATION_VIEW_COL_XALIGN,

    AML_APPLICATION_VIEW_COL_NUMBER
} AmlApplicationViewColumns;


AmlApplicationView *aml_application_view_construct(GType object_type)
{
    AmlApplicationView *self = NULL;
    self = (AmlApplicationView *) g_object_new(object_type, NULL);
    gtk_container_add(GTK_CONTAINER(self),
                      GTK_WIDGET(self->priv->appView));
    return self;
}


AmlApplicationView *aml_application_view_new(void)
{
    return aml_application_view_construct(TYPE_AML_APPLICATION_VIEW);
}


static void aml_application_view_class_init(AmlApplicationViewClass *
                                            klass)
{
    aml_application_view_parent_class = g_type_class_peek_parent(klass);
    g_type_class_add_private(klass, sizeof(AmlApplicationViewPrivate));
    G_OBJECT_CLASS(klass)->finalize = aml_application_view_finalize;
}


static void aml_application_view_instance_init(AmlApplicationView * self)
{
    self->priv = AML_APPLICATION_VIEW_GET_PRIVATE(self);

    AmlApplicationViewPrivate *priv = self->priv;
    priv->appStore = (GtkListStore *)
        gtk_list_store_new(AML_APPLICATION_VIEW_COL_NUMBER,
                           GDK_TYPE_PIXBUF, G_TYPE_STRING, G_TYPE_STRING,
                           G_TYPE_FLOAT);
    priv->appView = (GtkTreeView *)
        gtk_tree_view_new_with_model(GTK_TREE_MODEL(priv->appStore));
    g_object_ref_sink(priv->appStore);
    g_object_ref_sink(priv->appView);
}


static void aml_application_view_finalize(GObject * obj)
{
    AmlApplicationView *self;
    self =
        G_TYPE_CHECK_INSTANCE_CAST(obj, TYPE_AML_APPLICATION_VIEW,
                                   AmlApplicationView);
    _g_object_unref0(self->priv->appView);
    _g_object_unref0(self->priv->appStore);
    G_OBJECT_CLASS(aml_application_view_parent_class)->finalize(obj);
}


GType aml_application_view_get_type(void)
{
    static volatile gsize aml_application_view_type_id__volatile = 0;
    if (g_once_init_enter(&aml_application_view_type_id__volatile)) {
        static const GTypeInfo g_define_type_info =
            { sizeof(AmlApplicationViewClass), (GBaseInitFunc) NULL,
            (GBaseFinalizeFunc) NULL,
            (GClassInitFunc) aml_application_view_class_init,
            (GClassFinalizeFunc) NULL, NULL, sizeof(AmlApplicationView), 0,
            (GInstanceInitFunc) aml_application_view_instance_init, NULL
        };
        GType aml_application_view_type_id;
        aml_application_view_type_id =
            g_type_register_static(GTK_TYPE_SCROLLED_WINDOW,
                                   "AmlApplicationView",
                                   &g_define_type_info, 0);
        g_once_init_leave(&aml_application_view_type_id__volatile,
                          aml_application_view_type_id);
    }
    return aml_application_view_type_id__volatile;
}
