/* lcaboutdialog.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __LCABOUTDIALOG_H__
#define __LCABOUTDIALOG_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS
#define TYPE_LC_ABOUT_DIALOG (lc_about_dialog_get_type ())
#define LC_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LC_ABOUT_DIALOG, LcAboutDialog))
#define LC_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LC_ABOUT_DIALOG, LcAboutDialogClass))
#define IS_LC_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LC_ABOUT_DIALOG))
#define IS_LC_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LC_ABOUT_DIALOG))
#define LC_ABOUT_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LC_ABOUT_DIALOG, LcAboutDialogClass))
typedef struct _LcAboutDialog LcAboutDialog;
typedef struct _LcAboutDialogClass LcAboutDialogClass;
typedef struct _LcAboutDialogPrivate LcAboutDialogPrivate;

struct _LcAboutDialog {
    GtkAboutDialog parent_instance;
    LcAboutDialogPrivate *priv;
};

struct _LcAboutDialogClass {
    GtkAboutDialogClass parent_class;
};


GType lc_about_dialog_get_type(void) G_GNUC_CONST;
LcAboutDialog *lc_about_dialog_new(void);
LcAboutDialog *lc_about_dialog_construct(GType object_type);

#define lc_about_dialog_run(dialog)    gtk_dialog_run(GTK_DIALOG(dialog))
#define lc_about_dialog_destroy(dialog) gtk_widget_destroy(GTK_WIDGET(dialog))


G_END_DECLS
#endif
