/* lcaboutdialog.c generated by valac 0.20.1, the Vala compiler
 * generated from lcaboutdialog.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "lcaboutdialog.h"

const static gchar *LC_AUTHORS[] = {
    "Wiky L (wiiiky@yeah.net)",
    NULL
};


static gpointer lc_about_dialog_parent_class = NULL;

enum {
    LC_ABOUT_DIALOG_DUMMY_PROPERTY
};


LcAboutDialog *lc_about_dialog_construct(GType object_type)
{
    LcAboutDialog *self = NULL;
    self = (LcAboutDialog *) g_object_new(object_type, NULL);
    return self;
}


LcAboutDialog *lc_about_dialog_new(void)
{
    return lc_about_dialog_construct(TYPE_LC_ABOUT_DIALOG);
}


static void lc_about_dialog_class_init(LcAboutDialogClass * klass)
{
    lc_about_dialog_parent_class = g_type_class_peek_parent(klass);
}


static void lc_about_dialog_instance_init(LcAboutDialog * self)
{
    gtk_about_dialog_set_program_name(GTK_ABOUT_DIALOG(self),
                                      PROGRAM_NAME);
    gtk_about_dialog_set_version(GTK_ABOUT_DIALOG(self), LC_VERSION);
    gtk_about_dialog_set_license_type(GTK_ABOUT_DIALOG(self),
                                      GTK_LICENSE_GPL_3_0);
    gtk_about_dialog_set_copyright(GTK_ABOUT_DIALOG(self), LC_COPYRIGH);
    gtk_about_dialog_set_comments(GTK_ABOUT_DIALOG(self), LC_COMMENTS);
    gtk_about_dialog_set_website(GTK_ABOUT_DIALOG(self), LC_WEBSITE);
    gtk_about_dialog_set_authors(GTK_ABOUT_DIALOG(self), LC_AUTHORS);
}


GType lc_about_dialog_get_type(void)
{
    static volatile gsize lc_about_dialog_type_id__volatile = 0;
    if (g_once_init_enter(&lc_about_dialog_type_id__volatile)) {
        static const GTypeInfo g_define_type_info =
            { sizeof(LcAboutDialogClass), (GBaseInitFunc) NULL,
            (GBaseFinalizeFunc) NULL,
            (GClassInitFunc) lc_about_dialog_class_init,
            (GClassFinalizeFunc) NULL,
            NULL, sizeof(LcAboutDialog), 0,
            (GInstanceInitFunc) lc_about_dialog_instance_init, NULL
        };
        GType lc_about_dialog_type_id;
        lc_about_dialog_type_id =
            g_type_register_static(GTK_TYPE_ABOUT_DIALOG, "LcAboutDialog",
                                   &g_define_type_info, 0);
        g_once_init_leave(&lc_about_dialog_type_id__volatile,
                          lc_about_dialog_type_id);
    }
    return lc_about_dialog_type_id__volatile;
}
