/* LcApplicationView.c generated by valac 0.20.1, the Vala compiler
 * generated from LcApplicationView.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "lcapplicationview.h"
#include "lcutil.h"
#include "lccommander.h"
#include <gtk/gtk.h>
#include <gtk-2.0/gtk/gtktreemodel.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LcApplicationViewPrivate {
    GtkTreeView *appView;
    GtkListStore *appStore;

    gboolean loading;
};

#define lc_application_view_get_list_store(self)    ((self)->priv->appStore)
#define lc_application_view_get_tree_view(self)     ((self)->priv->appView)


static gpointer lc_application_view_parent_class = NULL;

#define LC_APPLICATION_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LC_APPLICATION_VIEW, LcApplicationViewPrivate))
enum {
    LC_APPLICATION_VIEW_DUMMY_PROPERTY
};
static void lc_application_view_finalize(GObject * obj);

typedef enum {
    LC_APPLICATION_VIEW_COL_ICON,   /*图标 */
    LC_APPLICATION_VIEW_COL_NAME,   /*应用名 */
    LC_APPLICATION_VIEW_COL_VERSION,    /*版本号 */
    LC_APPLICATION_VIEW_COL_PACKAGE,    /* 包名 */

    LC_APPLICATION_VIEW_COL_XALIGN,

    LC_APPLICATION_VIEW_COL_FLAG,   /* 标记位, used in lc_application_view_update */
    LC_APPLICATION_VIEW_COL_NUMBER
} LcApplicationViewColumns;

#define COLUMN_ICON_WIDTH   (100)
#define COLUMN_NAME_WIDTH   (150)
#define COLUMN_VERSION_WIDTH (120)
#define COLUMN_PACKAGE_WIDTH (140)


LcApplicationView *lc_application_view_construct(GType object_type)
{
    LcApplicationView *self = NULL;
    self = (LcApplicationView *) g_object_new(object_type, NULL);
    gtk_container_add(GTK_CONTAINER(self),
                      GTK_WIDGET(self->priv->appView));
    return self;
}


LcApplicationView *lc_application_view_new(void)
{
    return lc_application_view_construct(TYPE_LC_APPLICATION_VIEW);
}


static void lc_application_view_class_init(LcApplicationViewClass * klass)
{
    lc_application_view_parent_class = g_type_class_peek_parent(klass);
    g_type_class_add_private(klass, sizeof(LcApplicationViewPrivate));
    G_OBJECT_CLASS(klass)->finalize = lc_application_view_finalize;
}


static void lc_application_view_instance_init(LcApplicationView * self)
{
    self->priv = LC_APPLICATION_VIEW_GET_PRIVATE(self);

    LcApplicationViewPrivate *priv = self->priv;

    priv->loading = FALSE;
    priv->appStore = (GtkListStore *)
        gtk_list_store_new(LC_APPLICATION_VIEW_COL_NUMBER,
                           GDK_TYPE_PIXBUF, G_TYPE_STRING, G_TYPE_STRING,
                           G_TYPE_STRING, G_TYPE_FLOAT, G_TYPE_INT);
    priv->appView = (GtkTreeView *)
        gtk_tree_view_new_with_model(GTK_TREE_MODEL(priv->appStore));
    g_object_ref_sink(priv->appStore);
    g_object_ref_sink(priv->appView);

    GtkCellRenderer *renderer;
    GtkTreeViewColumn *column;
    renderer = gtk_cell_renderer_pixbuf_new();
    column = gtk_tree_view_column_new_with_attributes("ICON", renderer,
                                                      "pixbuf",
                                                      LC_APPLICATION_VIEW_COL_ICON,
                                                      NULL);
    gtk_tree_view_column_set_fixed_width(column, COLUMN_ICON_WIDTH);
    gtk_tree_view_append_column(priv->appView, column);

    renderer = gtk_cell_renderer_text_new();
    column = gtk_tree_view_column_new_with_attributes("NAME", renderer,
                                                      "text",
                                                      LC_APPLICATION_VIEW_COL_NAME,
                                                      "xalign",
                                                      LC_APPLICATION_VIEW_COL_XALIGN,
                                                      NULL);
    gtk_tree_view_column_set_fixed_width(column, COLUMN_NAME_WIDTH);
    gtk_tree_view_append_column(priv->appView, column);

    renderer = gtk_cell_renderer_text_new();
    column = gtk_tree_view_column_new_with_attributes("VERSION", renderer,
                                                      "text",
                                                      LC_APPLICATION_VIEW_COL_VERSION,
                                                      "xalign",
                                                      LC_APPLICATION_VIEW_COL_XALIGN,
                                                      NULL);
    gtk_tree_view_column_set_fixed_width(column, COLUMN_VERSION_WIDTH);
    gtk_tree_view_append_column(priv->appView, column);

    renderer = gtk_cell_renderer_text_new();
    column = gtk_tree_view_column_new_with_attributes("PACKAGE", renderer,
                                                      "text",
                                                      LC_APPLICATION_VIEW_COL_PACKAGE,
                                                      "xalign",
                                                      LC_APPLICATION_VIEW_COL_XALIGN,
                                                      NULL);
    gtk_tree_view_column_set_fixed_width(column, COLUMN_PACKAGE_WIDTH);
    gtk_tree_view_append_column(priv->appView, column);
}


static void lc_application_view_finalize(GObject * obj)
{
    LcApplicationView *self;
    self =
        G_TYPE_CHECK_INSTANCE_CAST(obj, TYPE_LC_APPLICATION_VIEW,
                                   LcApplicationView);
    _g_object_unref0(self->priv->appView);
    _g_object_unref0(self->priv->appStore);
    G_OBJECT_CLASS(lc_application_view_parent_class)->finalize(obj);
}


GType lc_application_view_get_type(void)
{
    static volatile gsize lc_application_view_type_id__volatile = 0;
    if (g_once_init_enter(&lc_application_view_type_id__volatile)) {
        static const GTypeInfo g_define_type_info =
            { sizeof(LcApplicationViewClass), (GBaseInitFunc) NULL,
            (GBaseFinalizeFunc) NULL,
            (GClassInitFunc) lc_application_view_class_init,
            (GClassFinalizeFunc) NULL, NULL, sizeof(LcApplicationView), 0,
            (GInstanceInitFunc) lc_application_view_instance_init, NULL
        };
        GType lc_application_view_type_id;
        lc_application_view_type_id =
            g_type_register_static(GTK_TYPE_SCROLLED_WINDOW,
                                   "LcApplicationView",
                                   &g_define_type_info, 0);
        g_once_init_leave(&lc_application_view_type_id__volatile,
                          lc_application_view_type_id);
    }
    return lc_application_view_type_id__volatile;
}

static void onIcon(const gchar * cmd, GByteArray * array,
                   gpointer user_data)
{
    GBytes *bytes = lc_util_get_bytes_from_byte_array(array);
    if (bytes == NULL) {
        g_warning("Connection Problem! Failed to get icon");
        return;
    }
    if (lc_protocol_get_result_from_bytes(bytes) !=
        LC_PROTOCOL_RESULT_OKAY) {
        g_warning("Protocol Problem! Failed to get icon");
        g_bytes_unref(bytes);
        return;
    }
    /* TODO */
    gsize size;
    gchar *content = (gchar *) g_bytes_unref_to_data(bytes, &size);
    const gchar *path =
        lc_util_get_image_cache_path_by_name((gchar *) user_data);
    GFile *file = g_file_new_for_path(path);
    g_file_replace_contents(file, content + LC_PROTOCOL_HDR_LEN,
                            size - LC_PROTOCOL_HDR_LEN, NULL, FALSE,
                            G_FILE_CREATE_NONE, NULL, NULL, NULL);
    g_free(content);
}

/*
 * update ALl application infomation
 * 
 * remove update and insert
 */
typedef struct {
    gchar *packageName;
    GtkTreeIter *iter;
    GtkListStore *store;
} LcIconData;
LcIconData *lc_icon_data_new(const gchar * packageName, GtkTreeIter * iter,
                             GtkListStore * store)
{
    LcIconData *icon = (LcIconData *) g_malloc(sizeof(LcIconData));
    icon->packageName = g_strdup(packageName);
    icon->iter = gtk_tree_iter_copy(iter);
    icon->store = store;

    return icon;
}

void lc_icon_data_free(LcIconData * icon)
{
    g_free(icon->packageName);
    gtk_tree_iter_free(icon->iter);
    g_free(icon);
}

void lc_application_view_update(LcApplicationView * self, GList * list)
{
    if (list == NULL) {
        return;
    }
    GtkTreeIter iter;
    GtkTreeModel *model =
        (GtkTreeModel *) lc_application_view_get_list_store(self);
    GList *add = g_list_copy(list);
    if (gtk_tree_model_get_iter_first(model, &iter)) {
        while (gtk_list_store_iter_is_valid(GTK_LIST_STORE(model), &iter)) {
            gchar *package = NULL;
            gtk_tree_model_get(model, &iter,
                               LC_APPLICATION_VIEW_COL_PACKAGE, &package,
                               -1);
            LcProtocolApplication *app =
                lc_protocol_application_find(list, package);
            g_free(package);
            if (app == NULL) {
                /* not found, delete */
                gtk_list_store_remove(GTK_LIST_STORE(model), &iter);
            } else {
                /* found, update */
                gtk_list_store_set(GTK_LIST_STORE(model), &iter,
                                   LC_APPLICATION_VIEW_COL_NAME,
                                   app->appName,
                                   LC_APPLICATION_VIEW_COL_VERSION,
                                   app->version,
                                   LC_APPLICATION_VIEW_COL_PACKAGE,
                                   app->packageName, -1);
                gtk_tree_model_iter_next(model, &iter);
                add = g_list_remove(add, app);
            }
        }
    }

    /* add the new elements */
    GList *lp = add;
    while (lp) {
        LcProtocolApplication *app = lp->data;
        gtk_list_store_append(GTK_LIST_STORE(model), &iter);
        gtk_list_store_set(GTK_LIST_STORE(model), &iter,
                           LC_APPLICATION_VIEW_COL_NAME,
                           app->appName,
                           LC_APPLICATION_VIEW_COL_VERSION,
                           app->version,
                           LC_APPLICATION_VIEW_COL_PACKAGE,
                           app->packageName, -1);
        lp = g_list_next(lp);
    }
    g_list_free(add);
}

/*
 * 在应用列表中增加一项，不会检查是否重复
 */
void lc_application_view_append(LcApplicationView * self,
                                LcProtocolApplication * data)
{
    GtkListStore *store = self->priv->appStore;
    GtkTreeIter iter;

    gtk_list_store_append(store, &iter);
    gtk_list_store_set(store, &iter,
                       LC_APPLICATION_VIEW_COL_NAME,
                       data->appName,
                       LC_APPLICATION_VIEW_COL_VERSION,
                       data->version,
                       LC_APPLICATION_VIEW_COL_PACKAGE,
                       data->packageName, -1);
}

void lc_application_view_set_loading(LcApplicationView * self,
                                     gboolean loading)
{
    self->priv->loading = loading;
}

gboolean lc_application_view_is_loading(LcApplicationView * self)
{
    return self->priv->loading;
}
