/* lcapplicationrow.c generated by valac 0.22.1, the Vala compiler
 * generated from lcapplicationrow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "lcapplicationrow.h"
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LcApplicationRowPrivate {
	GtkGrid * grid;
	GtkImage* icon_image;
	GtkLabel* name_label;
	GtkLabel* version_label;
};

#define LC_APPLICATION_ROW_ICON_SIZE	(48)

#define lc_application_row_get_icon_image(self)	((self)->priv->icon_image)
#define lc_application_row_get_name_label(self)	((self)->priv->name_label)
#define lc_application_row_get_version_label(self) \
	((self)->priv->version_label)


static gpointer lc_application_row_parent_class = NULL;

#define LC_APPLICATION_ROW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LC_APPLICATION_ROW, LcApplicationRowPrivate))
enum  {
	LC_APPLICATION_ROW_DUMMY_PROPERTY
};
static void lc_application_row_finalize (GObject* obj);


LcApplicationRow* lc_application_row_construct (GType object_type) {
	LcApplicationRow * self = NULL;
	self = (LcApplicationRow*) g_object_new (object_type, NULL);
	return self;
}


LcApplicationRow* lc_application_row_new (void) {
	return lc_application_row_construct (TYPE_LC_APPLICATION_ROW);
}


static void lc_application_row_class_init (LcApplicationRowClass * klass) {
	lc_application_row_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LcApplicationRowPrivate));
	G_OBJECT_CLASS (klass)->finalize = lc_application_row_finalize;
}


static void lc_application_row_instance_init (LcApplicationRow * self) {
	self->priv = LC_APPLICATION_ROW_GET_PRIVATE (self);

	LcApplicationRowPrivate *priv=self->priv;

	priv->grid=(GtkGrid*)gtk_grid_new();
	/*gtk_grid_set_column_homogeneous(priv->grid,TRUE);*/
	gtk_container_set_border_width(GTK_CONTAINER(priv->grid),1);
	g_object_ref_sink(priv->grid);
	priv->icon_image = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (priv->icon_image);
	priv->name_label = (GtkLabel*) gtk_label_new ("");
	gtk_misc_set_alignment(GTK_MISC(priv->name_label),0.1,0.5);
	gtk_widget_set_size_request(GTK_WIDGET(priv->name_label),150,-1);
	g_object_ref_sink (priv->name_label);
	priv->version_label = (GtkLabel*) gtk_label_new ("");
	gtk_misc_set_alignment(GTK_MISC(priv->version_label),0.1,0.5);
	gtk_widget_set_size_request(GTK_WIDGET(priv->version_label),150,-1);
	g_object_ref_sink (priv->version_label);

	gtk_container_add(GTK_CONTAINER(self),GTK_WIDGET(priv->grid));

	gtk_grid_attach(priv->grid,GTK_WIDGET(priv->icon_image),
				0,0,1,1);
	gtk_grid_attach(priv->grid,GTK_WIDGET(priv->name_label),
				1,0,1,1);
	gtk_grid_attach(priv->grid,GTK_WIDGET(priv->version_label),
				2,0,1,1);
}


static void lc_application_row_finalize (GObject* obj) {
	LcApplicationRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LC_APPLICATION_ROW, LcApplicationRow);
	_g_object_unref0 (self->priv->grid);
	_g_object_unref0 (self->priv->icon_image);
	_g_object_unref0 (self->priv->name_label);
	_g_object_unref0 (self->priv->version_label);
	G_OBJECT_CLASS (lc_application_row_parent_class)->finalize (obj);
}


GType lc_application_row_get_type (void) {
	static volatile gsize lc_application_row_type_id__volatile = 0;
	if (g_once_init_enter (&lc_application_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LcApplicationRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lc_application_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LcApplicationRow), 0, (GInstanceInitFunc) lc_application_row_instance_init, NULL };
		GType lc_application_row_type_id;
		lc_application_row_type_id = g_type_register_static (GTK_TYPE_EVENT_BOX, "LcApplicationRow", &g_define_type_info, 0);
		g_once_init_leave (&lc_application_row_type_id__volatile, lc_application_row_type_id);
	}
	return lc_application_row_type_id__volatile;
}



LcApplicationRow *lc_application_row_new_full(const gchar *icon_path,
			const gchar *name,const gchar *version)
{
	LcApplicationRow *self=lc_application_row_new();
	GtkImage *icon_image=lc_application_row_get_icon_image(self);
	GtkLabel *name_label=lc_application_row_get_name_label(self);
	GtkLabel *version_label=lc_application_row_get_version_label(self);

	gtk_image_set_from_file(icon_image,icon_path);
	gtk_label_set_text(name_label,name);
	gtk_label_set_text(version_label,version);

	return self;
}
