/* lcinstalldialog.h generated by valac 0.22.1, the Vala compiler, do not modify */


#ifndef __LCINSTALLDIALOG_H__
#define __LCINSTALLDIALOG_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS
#define TYPE_LC_INSTALL_DIALOG (lc_install_dialog_get_type ())
#define LC_INSTALL_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LC_INSTALL_DIALOG, LcInstallDialog))
#define LC_INSTALL_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LC_INSTALL_DIALOG, LcInstallDialogClass))
#define IS_LC_INSTALL_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LC_INSTALL_DIALOG))
#define IS_LC_INSTALL_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LC_INSTALL_DIALOG))
#define LC_INSTALL_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LC_INSTALL_DIALOG, LcInstallDialogClass))
typedef struct _LcInstallDialog LcInstallDialog;
typedef struct _LcInstallDialogClass LcInstallDialogClass;
typedef struct _LcInstallDialogPrivate LcInstallDialogPrivate;

struct _LcInstallDialog {
    GtkDialog parent_instance;
    LcInstallDialogPrivate *priv;
};

struct _LcInstallDialogClass {
    GtkDialogClass parent_class;
};


GType lc_install_dialog_get_type(void) G_GNUC_CONST;
LcInstallDialog *lc_install_dialog_new(GtkWindow * parent);
LcInstallDialog *lc_install_dialog_construct(GType object_type,
                                             GtkWindow * parent);

#define lc_install_dialog_run(self) gtk_dialog_run(GTK_DIALOG(self))

G_END_DECLS
#endif
