/* lcmainwindow.c generated by valac 0.20.1, the Vala compiler
 * generated from lcmainwindow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "lcmainwindow.h"
#include "lctoolstack.h"
#include "lcapplicationview.h"
#include "lcaboutdialog.h"
#include "lcadb.h"
#include "lcsocket.h"
#include "lcutil.h"
#include "lccommander.h"
#include "libadb/sysdeps.h"
#include "libadb/adb_client.h"

#define MAINWINDOW_TITLE "Android Manager"
#define LILY_ACTIVITY_NAME   "org.wl.ll/.MainActivity"
#define LILY_APK_NAME    "app-debug.apk"

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define LC_MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LC_MAIN_WINDOW, LcMainWindowPrivate))

static gpointer lc_main_window_parent_class = NULL;

#define APPLICATION_VIEW_NAME "app"
#define APPLICATION_VIEW_TITLE "Applications"
#define SMS_VIEW_NAME   "sms"
#define SMS_VIEW_TITLE  "SMS"

static void lc_main_window_finalize(GObject * obj);

/* 创建菜单栏 */
static GtkWidget *lc_main_window_menu_bar(LcMainWindow * self);

static void onAboutMenuItemActivate(GtkMenuItem * item, gpointer data);
/* 界面切换 */
static void onContentStackChanged(GtkStack * stack, GParamSpec * ps,
                                  gpointer data);


enum {
    LC_MAIN_WINDOW_DUMMY_PROPERTY
};

struct _LcMainWindowPrivate {
    LcApplicationView *appView;
    LcToolStack *toolStack;
};


LcMainWindow *lc_main_window_construct(GType object_type)
{
    LcMainWindow *self = NULL;
    self = (LcMainWindow *) g_object_new(object_type, NULL);
    return self;
}


LcMainWindow *lc_main_window_new(void)
{
    return lc_main_window_construct(TYPE_LC_MAIN_WINDOW);
}


static void lc_main_window_class_init(LcMainWindowClass * klass)
{
    lc_main_window_parent_class = g_type_class_peek_parent(klass);
    g_type_class_add_private(klass, sizeof(LcMainWindowPrivate));
    G_OBJECT_CLASS(klass)->finalize = lc_main_window_finalize;
}

static void onMyPhonePageVisible(gboolean visible, gpointer user_data)
{
    if (visible) {
        g_message("Come on, My Android!");
    }
}

static void lc_main_window_instance_init(LcMainWindow * self)
{
    self->priv = LC_MAIN_WINDOW_GET_PRIVATE(self);

    gtk_window_set_default_size(GTK_WINDOW(self), 960, 640);
    gtk_window_set_position(GTK_WINDOW(self), GTK_WIN_POS_CENTER);
    gtk_window_set_title(GTK_WINDOW(self), MAINWINDOW_TITLE);
    g_signal_connect(G_OBJECT(self), "destroy",
                     G_CALLBACK(gtk_main_quit), NULL);

    GtkWidget *rootBox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_container_add(GTK_CONTAINER(self), rootBox);

    gtk_box_pack_start(GTK_BOX(rootBox), lc_main_window_menu_bar(self),
                       FALSE, FALSE, 0);

    self->priv->toolStack = lc_tool_stack_new();
    gtk_box_pack_start(GTK_BOX(rootBox),
                       GTK_WIDGET(self->priv->toolStack), TRUE, TRUE, 0);
    g_object_ref_sink(self->priv->toolStack);

    self->priv->appView = lc_application_view_new();
    g_object_ref_sink(self->priv->appView);

    lc_tool_stack_append(self->priv->toolStack,
                         gtk_image_new_from_file
                         ("/home/wiky/Documents/CODE/Git/lucy/res/smartphone.svg"),
                         "My Phone", gtk_label_new("My Phone"),
                         onMyPhonePageVisible, self);
    lc_tool_stack_append(self->priv->toolStack,
                         gtk_image_new_from_file
                         ("/home/wiky/Documents/CODE/Git/lucy/res/computer.svg"),
                         "Applications", GTK_WIDGET(self->priv->appView),
                         NULL, NULL);
}

static void lc_main_window_finalize(GObject * obj)
{
    LcMainWindow *self =
        G_TYPE_CHECK_INSTANCE_CAST(obj, TYPE_LC_MAIN_WINDOW,
                                   LcMainWindow);
    _g_object_unref0(self->priv->appView);
    _g_object_unref0(self->priv->toolStack);
    G_OBJECT_CLASS(lc_main_window_parent_class)->finalize(obj);
}


GType lc_main_window_get_type(void)
{
    static volatile gsize lc_main_window_type_id__volatile = 0;
    if (g_once_init_enter(&lc_main_window_type_id__volatile)) {
        static const GTypeInfo g_define_type_info =
            { sizeof(LcMainWindowClass), (GBaseInitFunc) NULL,
            (GBaseFinalizeFunc) NULL,
            (GClassInitFunc) lc_main_window_class_init,
            (GClassFinalizeFunc) NULL,
            NULL, sizeof(LcMainWindow), 0,
            (GInstanceInitFunc) lc_main_window_instance_init, NULL
        };
        GType lc_main_window_type_id;
        lc_main_window_type_id =
            g_type_register_static(GTK_TYPE_WINDOW, "LcMainWindow",
                                   &g_define_type_info, 0);
        g_once_init_leave(&lc_main_window_type_id__volatile,
                          lc_main_window_type_id);
    }
    return lc_main_window_type_id__volatile;
}

/*创建菜单栏*/
static GtkWidget *lc_main_window_menu_bar(LcMainWindow * self)
{
    GtkWidget *menuBar = gtk_menu_bar_new();
    GtkWidget *aboutItem = gtk_menu_item_new_with_mnemonic("_About");
    gtk_menu_shell_append(GTK_MENU_SHELL(menuBar), aboutItem);

    GtkWidget *aboutMenu = gtk_menu_new();
    gtk_menu_item_set_submenu(GTK_MENU_ITEM(aboutItem), aboutMenu);

    GtkWidget *_aboutItem = gtk_menu_item_new_with_mnemonic("_About");
    gtk_menu_shell_append(GTK_MENU_SHELL(aboutMenu), _aboutItem);
    g_signal_connect(G_OBJECT(_aboutItem), "activate",
                     G_CALLBACK(onAboutMenuItemActivate), NULL);

    return menuBar;
}

/*About菜单项激活后的回调函数*/
static void onAboutMenuItemActivate(GtkMenuItem * item, gpointer data)
{
    LcAboutDialog *dialog = lc_about_dialog_new();
    lc_about_dialog_run(dialog);
    lc_about_dialog_destroy(dialog);
}

void lc_main_window_show(LcMainWindow * window)
{
    gtk_widget_show_all(GTK_WIDGET(window));
    lc_main_window_start_server(window);
    gtk_main();
}

static void onActivityStartFinal(GObject * source_object,
                                 GAsyncResult * res, gpointer user_data)
{
    if (lc_adb_am_start_finish(res)) {
        g_error("Failed to start lily final!");
    }
}

static void onInstallLily(GObject * source_object,
                          GAsyncResult * res, gpointer user_data)
{
    int ret = lc_adb_install_app_finish(res);
    if (ret) {
        g_error("Failed to install apk: %s", adb_error());
        return;
    }
    lc_adb_am_start(LILY_ACTIVITY_NAME, onActivityStartFinal, user_data);
}

static const gchar *getLilyAPKPath()
{
    const gchar *pkgdata = PACKAGE_DATA_DIR "/apk/" LILY_APK_NAME;
    const gchar *srcdata = PACKAGE_SRC_DIR "/../res/apk/" LILY_APK_NAME;

    if (g_file_test(pkgdata, G_FILE_TEST_EXISTS)) {
        return pkgdata;
    } else if (g_file_test(srcdata, G_FILE_TEST_EXISTS)) {
        return srcdata;
    }
    g_warning(PACKAGE_DATA_DIR "/apk/" LILY_APK_NAME);
    g_warning(PACKAGE_SRC_DIR "/../res/apk/" LILY_APK_NAME);
    return NULL;
}

static void onApplications(GObject * source_object,
                           GAsyncResult * res, gpointer user_data)
{
    GByteArray *array = lc_commander_send_command_finish(res);
    gchar *result = lc_util_get_string_from_byte_array(array, NULL);
    if (result == NULL) {
        g_warning("Connection Problem while 'applications'");
        return;
    }
    if (lc_protocol_get_result_from_string(result) !=
        LC_PROTOCOL_RESULT_OKAY) {
        g_warning("Command 'applications' Failed:%s", result);
    } else {
        LcMainWindow *self = (LcMainWindow *) user_data;
        LcApplicationView *appView = self->priv->appView;
        GList *list = lc_protocol_create_application_list(result + 4);
        GList *lp = list;
        while (lp) {
            LcProtocolApplication *info =
                (LcProtocolApplication *) lp->data;
            lc_application_view_append(appView, info);
            g_message("%s", info->appName);
            lp = g_list_next(lp);
        }
        lc_protocol_free_application_list(list);
    }
    g_free(result);
}


static void onActivityStart(GObject * source_object,
                            GAsyncResult * res, gpointer user_data)
{
    if (lc_adb_am_start_finish(res)) {
        g_message("Failed to start Lily!");
        const gchar *apkpath = getLilyAPKPath();
        if (apkpath == NULL) {
            g_error("Lily apk file is missing!!");
        }
        lc_adb_install_app(apkpath, onInstallLily, user_data);
    } else {
        lc_commander_send_command("applications\n", onApplications,
                                  user_data);
    }
}

static void onForward(GObject * source_object,
                      GAsyncResult * res, gpointer user_data)
{
    int ret = lc_adb_forward_finish(res);
    if (ret == 0) {
        /* OK */
    } else {
        g_error("Failed to forward tcp port! %s\n", adb_error());
    }
}

static void onStartServer(GObject * source_object,
                          GAsyncResult * res, gpointer user_data)
{
    int ret = lc_adb_start_server_finish(res);
    if (ret == 0) {
        /* OK */
        lc_adb_forward(ADB_FORWARD_LOCAL, ADB_FORWARD_REMOTE,
                       onForward, user_data);
        lc_adb_am_start(LILY_ACTIVITY_NAME, onActivityStart, user_data);
    } else {
        /* ERROR, failed to start(or connect to) adb server */
        g_error("Failed to start adb server! %s\n", adb_error());
    }
}

void lc_main_window_start_server(LcMainWindow * window)
{
    lc_adb_start_server(onStartServer, window);
}
