/* lcmyphone.c generated by valac 0.22.1, the Vala compiler
 * generated from lcmyphone.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "lcmyphone.h"
#include "lcutil.h"
#include <gtk/gtk.h>
#include <gtk-2.0/gtk/gtkbutton.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LcMyPhonePrivate {
    GtkGrid *disconnected;
    GtkGrid *connected;
    GtkButton *connectButton;

    /* connected widget */
    GtkLabel *phoneBrand;
    GtkLabel *phoneModel;
};

#define STACK_NAME_DISCONNECTED "disconnected"
#define STACK_NAME_CONNECTED	"connected"


static gpointer lc_my_phone_parent_class = NULL;

#define LC_MY_PHONE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LC_MY_PHONE, LcMyPhonePrivate))
enum {
    LC_MY_PHONE_DUMMY_PROPERTY
};
static void lc_my_phone_finalize(GObject * obj);


LcMyPhone *lc_my_phone_construct(GType object_type)
{
    LcMyPhone *self = NULL;
    self = (LcMyPhone *) g_object_new(object_type,
                                      "transition-duration", 1000,
                                      "transition-type",
                                      GTK_STACK_TRANSITION_TYPE_CROSSFADE,
                                      NULL);
    return self;
}


LcMyPhone *lc_my_phone_new(void)
{
    return lc_my_phone_construct(TYPE_LC_MY_PHONE);
}


static void lc_my_phone_class_init(LcMyPhoneClass * klass)
{
    lc_my_phone_parent_class = g_type_class_peek_parent(klass);
    g_type_class_add_private(klass, sizeof(LcMyPhonePrivate));
    G_OBJECT_CLASS(klass)->finalize = lc_my_phone_finalize;
}

static void lc_my_phone_disconnect_init(LcMyPhone * self);
static void lc_my_phone_connect_init(LcMyPhone * self);

static void lc_my_phone_instance_init(LcMyPhone * self)
{
    self->priv = LC_MY_PHONE_GET_PRIVATE(self);

    lc_my_phone_disconnect_init(self);
    lc_my_phone_connect_init(self);

    gtk_stack_add_named(GTK_STACK(self),
                        GTK_WIDGET(self->priv->disconnected),
                        STACK_NAME_DISCONNECTED);
    gtk_stack_add_named(GTK_STACK(self), GTK_WIDGET(self->priv->connected),
                        STACK_NAME_CONNECTED);

    gtk_stack_set_visible_child_name(GTK_STACK(self),
                                     STACK_NAME_DISCONNECTED);
}


static void lc_my_phone_disconnect_init(LcMyPhone * self)
{
    GtkGrid *dc = (GtkGrid *) gtk_grid_new();

    gtk_widget_set_name(GTK_WIDGET(dc), "grid");

    GtkWidget *button = gtk_button_new_with_label("Connect");
    gtk_widget_set_name(button, "connect");
    gtk_grid_attach(dc, button, 0, 1, 1, 1);

    gtk_widget_set_hexpand(button, TRUE);
    gtk_widget_set_halign(button, GTK_ALIGN_CENTER);
    gtk_widget_set_margin_top(button, 300);

    lc_util_load_css(GTK_WIDGET(dc), "css/disconnected.css");

    gtk_widget_show_all(GTK_WIDGET(dc));

    self->priv->disconnected = dc;
    g_object_ref_sink(self->priv->disconnected);
    self->priv->connectButton = GTK_BUTTON(button);
    g_object_ref_sink(self->priv->connectButton);
}

static void lc_my_phone_connect_init(LcMyPhone * self)
{
    GtkGrid *cn = (GtkGrid *) gtk_grid_new();
    GtkWidget *brand = gtk_label_new("");
    GtkWidget *model = gtk_label_new("");
    gtk_grid_attach(cn, brand, 0, 0, 1, 1);
    gtk_grid_attach(cn, model, 0, 1, 1, 1);

    gtk_widget_show_all(GTK_WIDGET(cn));

    self->priv->connected = cn;
    self->priv->phoneBrand = (GtkLabel *) brand;
    self->priv->phoneModel = (GtkLabel *) model;
    g_object_ref_sink(self->priv->phoneBrand);
    g_object_ref_sink(self->priv->phoneModel);
    g_object_ref_sink(self->priv->connected);
}

static void lc_my_phone_finalize(GObject * obj)
{
    LcMyPhone *self;
    self = G_TYPE_CHECK_INSTANCE_CAST(obj, TYPE_LC_MY_PHONE, LcMyPhone);
    _g_object_unref0(self->priv->disconnected);
    _g_object_unref0(self->priv->connected);
    _g_object_unref0(self->priv->connectButton);
    G_OBJECT_CLASS(lc_my_phone_parent_class)->finalize(obj);
}


GType lc_my_phone_get_type(void)
{
    static volatile gsize lc_my_phone_type_id__volatile = 0;
    if (g_once_init_enter(&lc_my_phone_type_id__volatile)) {
        static const GTypeInfo g_define_type_info =
            { sizeof(LcMyPhoneClass), (GBaseInitFunc) NULL,
            (GBaseFinalizeFunc) NULL,
            (GClassInitFunc) lc_my_phone_class_init,
            (GClassFinalizeFunc) NULL, NULL,
            sizeof(LcMyPhone), 0,
            (GInstanceInitFunc) lc_my_phone_instance_init, NULL
        };
        GType lc_my_phone_type_id;
        lc_my_phone_type_id =
            g_type_register_static(GTK_TYPE_STACK, "LcMyPhone",
                                   &g_define_type_info, 0);
        g_once_init_leave(&lc_my_phone_type_id__volatile,
                          lc_my_phone_type_id);
    }
    return lc_my_phone_type_id__volatile;
}


void lc_my_phone_set_connect_callback(LcMyPhone * self, GCallback callback,
                                      gpointer user_data)
{
    g_signal_connect(G_OBJECT(self->priv->connectButton), "clicked",
                     callback, user_data);
}

void lc_my_phone_show_disconnect(LcMyPhone * self)
{
    gtk_stack_set_visible_child_name(GTK_STACK(self),
                                     STACK_NAME_DISCONNECTED);
}

void lc_my_phone_show_connecting(LcMyPhone * self)
{
    //lc_my_phone_set_connecting_timeout(self);
    gtk_widget_set_sensitive(GTK_WIDGET(self->priv->connectButton), FALSE);
    gtk_button_set_label(self->priv->connectButton, "Connecting");
    gtk_stack_set_visible_child_name(GTK_STACK(self),
                                     STACK_NAME_DISCONNECTED);
}

void lc_my_phone_show_connected(LcMyPhone * self)
{
    gtk_stack_set_visible_child_name(GTK_STACK(self),
                                     STACK_NAME_CONNECTED);
}

void lc_my_phone_show_connected_with_info(LcMyPhone * self,
                                          LcProtocolPhone * phone)
{
    lc_my_phone_show_connected(self);

    gtk_label_set_text(self->priv->phoneBrand, phone->brand);
    gtk_label_set_text(self->priv->phoneModel, phone->model);
}
