/* lcsmsview.h generated by valac 0.22.1, the Vala compiler, do not modify */


#ifndef __LCSMSVIEW_H__
#define __LCSMSVIEW_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS
#define TYPE_LC_SMS_VIEW (lc_sms_view_get_type ())
#define LC_SMS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LC_SMS_VIEW, LcSMSView))
#define LC_SMS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LC_SMS_VIEW, LcSMSViewClass))
#define IS_LC_SMS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LC_SMS_VIEW))
#define IS_LC_SMS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LC_SMS_VIEW))
#define LC_SMS_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LC_SMS_VIEW, LcSMSViewClass))
typedef struct _LcSMSView LcSMSView;
typedef struct _LcSMSViewClass LcSMSViewClass;
typedef struct _LcSMSViewPrivate LcSMSViewPrivate;

struct _LcSMSView {
    GtkScrolledWindow parent_instance;
    LcSMSViewPrivate *priv;
};

struct _LcSMSViewClass {
    GtkScrolledWindowClass parent_class;
};


GType lc_sms_view_get_type(void) G_GNUC_CONST;
LcSMSView *lc_sms_view_new(GList * list);
LcSMSView *lc_sms_view_construct(GType object_type, GList * list);


G_END_DECLS
#endif
