/* lcsmsbox.h generated by valac 0.22.1, the Vala compiler, do not modify */


#ifndef __LCSMSBOX_H__
#define __LCSMSBOX_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS


#define TYPE_LC_SMS_BOX (lc_sms_box_get_type ())
#define LC_SMS_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LC_SMS_BOX, LcSmsBox))
#define LC_SMS_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LC_SMS_BOX, LcSmsBoxClass))
#define IS_LC_SMS_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LC_SMS_BOX))
#define IS_LC_SMS_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LC_SMS_BOX))
#define LC_SMS_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LC_SMS_BOX, LcSmsBoxClass))

typedef struct _LcSmsBox LcSmsBox;
typedef struct _LcSmsBoxClass LcSmsBoxClass;
typedef struct _LcSmsBoxPrivate LcSmsBoxPrivate;

struct _LcSmsBox {
	GtkDrawingArea parent_instance;
	LcSmsBoxPrivate * priv;
};

struct _LcSmsBoxClass {
	GtkDrawingAreaClass parent_class;
};


GType lc_sms_box_get_type (void) G_GNUC_CONST;
LcSmsBox* lc_sms_box_new (void);
LcSmsBox* lc_sms_box_construct (GType object_type);


G_END_DECLS

#endif
