/* lcsmsbox.c generated by valac 0.22.1, the Vala compiler
 * generated from lcsmsbox.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "lcsmsbox.h"
#include <stdlib.h>
#include <string.h>

struct _LcSmsBoxPrivate {
	gchar* text;
};


static gpointer lc_sms_box_parent_class = NULL;

#define LC_SMS_BOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LC_SMS_BOX, LcSmsBoxPrivate))
enum  {
	LC_SMS_BOX_DUMMY_PROPERTY
};
static void lc_sms_box_finalize (GObject* obj);


LcSmsBox* lc_sms_box_construct (GType object_type) {
	LcSmsBox * self = NULL;
	self = (LcSmsBox*) g_object_new (object_type, NULL);
	return self;
}


LcSmsBox* lc_sms_box_new (void) {
	return lc_sms_box_construct (TYPE_LC_SMS_BOX);
}


static void lc_sms_box_class_init (LcSmsBoxClass * klass) {
	lc_sms_box_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LcSmsBoxPrivate));
	G_OBJECT_CLASS (klass)->finalize = lc_sms_box_finalize;
}


static void lc_sms_box_instance_init (LcSmsBox * self) {
	self->priv = LC_SMS_BOX_GET_PRIVATE (self);

	LcSmsBoxPrivate *priv=self->priv;

	priv->text=NULL;
}


static void lc_sms_box_finalize (GObject* obj) {
	LcSmsBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LC_SMS_BOX, LcSmsBox);
	g_free (self->priv->text);
	G_OBJECT_CLASS (lc_sms_box_parent_class)->finalize (obj);
}


GType lc_sms_box_get_type (void) {
	static volatile gsize lc_sms_box_type_id__volatile = 0;
	if (g_once_init_enter (&lc_sms_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LcSmsBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lc_sms_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LcSmsBox), 0, (GInstanceInitFunc) lc_sms_box_instance_init, NULL };
		GType lc_sms_box_type_id;
		lc_sms_box_type_id = g_type_register_static (GTK_TYPE_DRAWING_AREA, "LcSmsBox", &g_define_type_info, 0);
		g_once_init_leave (&lc_sms_box_type_id__volatile, lc_sms_box_type_id);
	}
	return lc_sms_box_type_id__volatile;
}



